/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Element,
} from '@stencil/core';

declare global {
  interface HTMLOckQrcodeElement extends HTMLStencilElement {
    'address': string;
    'amount': number;
    'deserializeURI': (uri: string) => { address: any; amount: any; label: any; vendorField: any; };
    'fromObject': (data: any) => Element;
    'getDataURL': (mime?: string) => string;
    'getURI': () => string;
    'label': string;
    'showLogo': boolean;
    'size': number;
    'validateURI': (uri: string) => RegExpExecArray;
    'vendorField': string;
  }
  var HTMLOckQrcodeElement: {
    prototype: HTMLOckQrcodeElement;
    new (): HTMLOckQrcodeElement;
  };
  interface HTMLElementTagNameMap {
    'ock-qrcode': HTMLOckQrcodeElement;
  }
  interface ElementTagNameMap {
    'ock-qrcode': HTMLOckQrcodeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ock-qrcode': JSXElements.OckQrcodeAttributes;
    }
  }
  namespace JSXElements {
    export interface OckQrcodeAttributes extends HTMLAttributes {
      'address'?: string;
      'amount'?: number;
      'label'?: string;
      'showLogo'?: boolean;
      'size'?: number;
      'vendorField'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
